In [2]:
from scripts.python.simulateCommunityModel import simulateCommunityModel
import pandas as pd

In [3]:
mu = 1 # growth rate
modelNames = ['Lachnospiraceae_species','Bacteroides_ovatus','Bifidobacterium_longum',
'Collinsella_aerofaciens','Escherichia_coli','Klebsiella_aerogenes','Muricomes_intestini','Parabacteroides_distasonis']
modelPaths = ['./Data/HDC/HDC1_gapseq/HDC_180_genome.xml',
'./Data/HDC/HDC1_gapseq/HDC_376_genome.xml',
'./Data/HDC/HDC1_gapseq/HDC_370_genome.xml',
'./Data/HDC/HDC1_gapseq/HDC_374_genome.xml',
'./Data/HDC/HDC1_gapseq/HDC_382_genome.xml',
'./Data/HDC/HDC1_gapseq/HDC_bin1.xml',
'./Data/HDC/HDC1_gapseq/HDC_380_genome.xml',
'./Data/HDC/HDC1_gapseq/HDC_378_genome.xml']
modelWeights = [0.000001,0.008976,0.000124,0.000007,0.000085,0.000121,0.000082,0.000426]

modelDetails = pd.DataFrame({'Name':modelNames,'Path':modelPaths,'weight':modelWeights})
modelDetails.head()

,Name,Path,weight
0,Lachnospiraceae_species,./Data/HDC/HDC1_gapseq/HDC_180_genome.xml,0.000001
1,Bacteroides_ovatus,./Data/HDC/HDC1_gapseq/HDC_376_genome.xml,0.008976
2,Bifidobacterium_longum,./Data/HDC/HDC1_gapseq/HDC_370_genome.xml,0.000124
3,Collinsella_aerofaciens,./Data/HDC/HDC1_gapseq/HDC_374_genome.xml,0.000007
4,Escherichia_coli,./Data/HDC/HDC1_gapseq/HDC_382_genome.xml,0.000085

In [4]:
# exchange reactions (from metabolomics data)
exchangeRate = pd.read_excel('./Data/HDC/HDC1_metabolomics_preliminary_formodelling2.xlsx')
exchangeRate['GF_conc'] = exchangeRate['GF_Mean (mmol per g)']
exchangeRate['Microbiome_conc'] = exchangeRate['HDC1_Mean (mmol per g)']
exchangeRate['GF_conc_sd'] = exchangeRate['GF_Standard deviation (mmol per g)']
exchangeRate['Microbiome_conc_sd'] = exchangeRate['HDC1_Standard deviation (mmol per g)']
exchangeRate.head()

,Quantified compounds,modelseed ID,HMDB ID,Metabolite present in gapseq model exchange reactions?,GF_Mean (mmol per g),GF_Standard deviation (mmol per g),HDC1_Mean (mmol per g),HDC1_Standard deviation (mmol per g),Consumed or produced?,GF_conc,Microbiome_conc,GF_conc_sd,Microbiome_conc_sd
0,Guanosine,cpd00311,HMDB0000133,Y,0.000523,0.000386,0.000284,0.000330,consumed,0.000523,0.000284,0.000386,0.000330
1,Argnine,cpd00051,HMDB0000517,Y,0.007678,0.006080,0.002062,0.001895,consumed,0.007678,0.002062,0.006080,0.001895
2,Asparagine,cpd00132,HMDB0000168,Y,0.007764,0.005528,0.000069,0.000080,consumed,0.007764,0.000069,0.005528,0.000080
3,Glutamine,cpd00053,HMDB0000641,Y,0.008064,0.005168,0.002055,0.001684,consumed,0.008064,0.002055,0.005168,0.001684
4,Glycine,cpd00033,HMDB0000123,Y,0.015165,0.011155,0.008150,0.006380,consumed,0.015165,0.008150,0.011155,0.006380

In [6]:
solution = simulateCommunityModel(modelDetails, exchangeRate, mu, solver='gurobi')

Set parameter Username

CobraSBMLError: Something went wrong reading the SBML model. Most likely the SBML model is not valid. Please check that your model is valid using the `cobra.io.sbml.validate_sbml_model` function or via the online validator at https://sbml.org/validator_servlet/ .
	`(model, errors) = validate_sbml_model(filename)`
If the model is valid and cannot be read please open an issue at https://github.com/opencobra/cobrapy/issues .

# The simulation is infeasible at this state

In [ ]:
# solution, merged_model = simulateCommunityModel(modelDetails, exchangeRate, mu, solver='glpk')

# The simulation is infeasible if sum of all the biomass has to be less than X0

In [ ]:
# solution, merged_model, df_biomass, df_metabolomics= simulateCommunityModel(modelDetails, exchangeRate, mu, solver='glpk')

# The simulation is feasible if stringent constraint is not applied on the exchange reactions. Here an lower bound is set.

In [ ]:
solution, merged_model, df_biomass, df_metabolomics= simulateCommunityModel(modelDetails, exchangeRate, mu, solver='glpk',beta=0.1)

'180_genome' is not a valid SBML 'SId'.
'376_genome' is not a valid SBML 'SId'.
'370_genome' is not a valid SBML 'SId'.
'374_genome' is not a valid SBML 'SId'.
'382_genome' is not a valid SBML 'SId'.
'380_genome' is not a valid SBML 'SId'.
'378_genome' is not a valid SBML 'SId'.

Comparing the actual and predicted biomass weights
                        Model     Predicted    Actual
0     Lachnospiraceae_species  1.000000e-06  0.000001
1          Bacteroides_ovatus  8.976000e-03  0.008976
2      Bifidobacterium_longum  1.240000e-04  0.000124
3     Collinsella_aerofaciens  7.000000e-06  0.000007
4            Escherichia_coli  8.500000e-05  0.000085
5        Klebsiella_aerogenes  1.210000e-04  0.000121
6         Muricomes_intestini  8.200000e-05  0.000082
7  Parabacteroides_distasonis  4.260000e-04  0.000426
Comparing the actual and predicted metabolomics consumption rates by the community
   Metabolite  Predicted    Actual
0    cpd00182  -0.000000  0.000037
1    cpd00367  -0.000000  0.000738
2    cpd00277   0.000002  0.000378
3    cpd00311  -0.000002  0.001237
4    cpd00246  -0.000028  0.000888
5    cpd00184  -0.000000  0.000745
6    cpd00035   0.006087  0.011093
7    cpd00051   0.003423  0.019182
8    cpd00132  -0.000000  0.018437
9    cpd00041   0.038632  0.009944
10   cpd00098  -0.000000  0.004166
11   cpd00053  -0.000000  0.017147
12   cpd00023   0.087618  0.030207
13   cpd00033   0.013234  0.034459
14   cpd00119   0.009441  0.013290
15   cpd00322  -0.000064  0.008250
16   cpd00359  -0.000000  0.000071
17   cpd00107   0.000349  0.012703
18   cpd00039   0.002384  0.028877
19   cpd00060   0.005300  0.002085
20   cpd00064  -0.000658  0.000406
21   cpd00066   0.001717  0.010062
22   cpd00129   0.001922  0.045481
23   cpd00054   0.027437  0.031370
24   cpd00264  -0.000000  0.000065
25   cpd00161   0.002824  0.048710
26   cpd00065   0.000532  0.002761
27   cpd00069   0.001285  0.006494
28   cpd00249  -0.000000  0.001582
29   cpd00156   0.006669  0.018720
30   cpd00136  -0.000000  0.000025
31   cpd00029   0.007289  0.107289
32   cpd00153  -0.000000  0.000099
33   cpd00211  -0.000636  0.001740
34   cpd00137  -0.000000  0.000057
35   cpd00300   0.004204  0.000188
36   cpd01217  -0.000000  0.000043
37   cpd00027  -0.000000  0.059214
38   cpd02733  -0.000000  0.000165
39   cpd01318  -0.000000  0.000009
40   cpd03047  -0.000000  0.002521
41   cpd03246  -0.000000  0.000188